#!/usr/bin/env bash
# Bash script that displays Best School 10 times, 9th iteration, display Hi
CONTADOR=1
while [ $CONTADOR -le 10 ]
do
    echo "Best School"
    if [ $CONTADOR -eq 9]
    then
        echo "Hi"
    fi
    let CONTADOR=$((CONTADOR+1))
done
